version: "3.7"
services:
  api_service:
    build: .
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - mysql_db
  mysql_db:
    image: "mysql:5.0"
    restart: always
    ports:
      - 3300:3301
    environment:
      MYSQL_DATABASE: hms
      MYSQL_USER: root
      MYSQL_PASSWORD: root
